services:
  # Productos
  products-micro:
    image: "nginx"
    restart: unless-stopped
    container_name: products-micro
    ports:
      - 8082:80
    networks:
      - products-network
      - microservices-network
    volumes:
      - "products-code:/var/www/html"
      - "products-nginx-conf:/etc/nginx/conf.d"

  products-db:
    image: mysql:5.7.33
    restart: unless-stopped
    container_name: products-db
    ports:
      - 33062:3306
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: $DB_DATABASEPRODUCTOS
      MYSQL_ROOT_PASSWORD: $DB_PASSWORDPRODUCTOS
    networks:
      - products-network
    volumes:
      - "products-db-data:/var/lib/mysql"

  products-app:
    build: ./productos/php/
    container_name: products-app
    restart: unless-stopped
    networks:
      - products-network
    volumes:
      - products-code:/var/www/html


  # Usuarios
  users-micro:
    image: "nginx"
    restart: unless-stopped
    container_name: users-micro
    ports:
      - 8081:80
    networks:
      - users-network      
      - microservices-network
    volumes:
      - "users-code:/var/www/html"
      - "users-nginx-conf:/etc/nginx/conf.d"

  users-db:
    image: mysql:5.7.33
    restart: unless-stopped
    container_name: users-db
    ports:
      - 33061:3306
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: $DB_DATABASEUSUARIOS
      MYSQL_ROOT_PASSWORD: $DB_PASSWORDUSUARIOS
    networks:
      - users-network
    volumes:
      - "users-db-data:/var/lib/mysql"

  users-app:
    build: ./usuarios/php/
    container_name: users-app
    restart: unless-stopped
    networks:
      - users-network
    volumes:
      - users-code:/var/www/html


  # Ventas
  sales-micro:
    image: "nginx"
    restart: unless-stopped
    container_name: sales-micro
    ports:
      - 8083:80
    networks:
      - sales-network      
      - microservices-network
    volumes:
      - "sales-code:/var/www/html"
      - "sales-nginx-conf:/etc/nginx/conf.d"

  sales-db:
    image: mysql:5.7.33
    restart: unless-stopped
    container_name: sales-db
    ports:
      - 33063:3306
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: $DB_DATABASESALES
      MYSQL_ROOT_PASSWORD: $DB_PASSWORDSALES
    networks:
      - sales-network
    volumes:
      - "sales-db-data:/var/lib/mysql"

  sales-app:
    build: ./ventas/php/
    container_name: sales-app
    restart: unless-stopped
    networks:
      - sales-network
    volumes:
      - sales-code:/var/www/html


  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices-network
      - products-network
      - sales-network
      - users-network

  kong:
    image: kong
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/kong/kong.yml"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    ports:
      - "7000:8000"
      - "7001:8001"
    volumes:
      - ./kong/kong.yml:/kong/kong.yml
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
  products-network:
    external: false
  users-network:
    external: false    
  sales-network:
    external: false

volumes:
  # Volumenes del micro de productos
  products-code:
    driver_opts:
      type: "none"
      o: "bind"
      device: '${PWD}/productos/php/code/'
  products-nginx-conf:
    driver_opts:
      type: "none"
      o: "bind"
      device: '${PWD}/productos/nginx/conf.d/'
  products-db-data:
  
  # Volumenes del micro de usuarios
  users-code:
    driver_opts:
      type: "none"
      o: "bind"
      device: '${PWD}/usuarios/php/code/'
  users-nginx-conf:
    driver_opts:
      type: "none"
      o: "bind"
      device: '${PWD}/usuarios/nginx/conf.d/'
  users-db-data:

  # Volumenes del micro de ventas
  sales-code:
    driver_opts:
      type: "none"
      o: "bind"
      device: "${PWD}/ventas/php/code/"
  sales-nginx-conf:
    driver_opts:
      type: "none"
      o: "bind"
      device: '${PWD}/ventas/nginx/conf.d/'
  sales-db-data: